### ISSUE TITLE
params object for hierachical time series empty

### ISSUE THREAD

**Issue by alexkowa** [statistikat/persephone#11]
returns only NULL ?! 

```
 obj_x13 <- per_x13(AirPassengers, "RSA3")
  ht <- per_hts(a = obj_x13,
                b = obj_x13,
                c = obj_x13,
                weights = c(2, 2, 2)
                )
ht$params
```

**Comment by GregorDeCillia** [comment]
The logic for the slot `$params` as well as `$set_options()` needs some updates. Currently per_hts objects don't behave like single objects in some regards (this is one of them).

I'll have a look at this soon
