### ISSUE TITLE
testthat failure

### ISSUE THREAD

**Issue by merangelik** [statistikat/persephone#25]
https://github.com/statistikat/persephone/blob/1f88d2a79182fdda9276770383c551e6206c5bdf/tests/testthat/test-hierarchical.R#L193

Is there a reason why the difference has to be <5?

Currently we would get:

`max(ht0$forecasts_indirect[, "y_f"] - ht0$forecasts_direct[, "y_f"])`
[1] 14.40176

**Comment by alexkowa** [comment]
Is that the 5 year maximum span for prediction from X13?

**Comment by merangelik** [comment]
No, its just the difference between direct and indirect forecasts:
```
ht0$forecasts_indirect[, "y_f"] - ht0$forecasts_direct[, "y_f"]
           Jan       Feb       Mar       Apr       May       Jun
1961  7.386688 14.401764  8.818477  2.451709 12.171386  9.681827
           Jul       Aug       Sep       Oct       Nov       Dec
1961  1.117395 14.052483  2.962225  7.616338  8.565156  0.344759
```

**Comment by alexkowa** [comment]
Don't know

**Comment by froehlich1** [comment]
I have no Idea! 
Where does this come from?
is it from the original RJDemetra code?

**Comment by froehlich1** [comment]
...oh, of course it cannot come from RJDemetra.

**Comment by merangelik** [comment]
Ok thank you, I'll get rid of it then for now
